---
title: "KMC_HW"
output:
  html_document: default
  pdf_document: default
---
library("ramify")
library(datasets)
library(stats)
library(dplyr)
data(iris)

```{r}
Xs <- as.data.frame(read.table(file="zipSample.txt", header=FALSE))

digit <- Xs[,1]
Xs <- Xs[,-1]
```

```{r}
getMeans <- function(Cprev, X,K){
  p = dim(X)[2]
  # create a K x P matrix for means
  M = matrix(data = 0, nrow = K, ncol = p)
  
  # combine X and C so we don't have to carry indices
  XC = cbind(X,Cprev)
  Ccol = p + 1 # cluster column number
  
  # form new means based on previous cluster assignments
  for (k in 1:K) {
    in_cluster_k = subset(XC,XC[,Ccol]==k)
    M[k,] = colMeans(in_cluster_k[,-Ccol])
  }
  
  return(M)
}

reCluster <- function(X,M,K){
  n = dim(X)[1]
  C = matrix(data = 0, nrow = n, ncol = 1)
  
  # for each sample calculate distance to each mean
  # assign cluster to that of closest mean
  for (i in 1:n) {
    eucdist = matrix(data = NA, nrow = 1, ncol = K)
    for (j in 1:K) {
      eucdist[j] = stats::dist(rbind(X[i,],M[j,]))
    }
    C[i] = ramify::argmin(eucdist)
  }
  return(C)
}

converged <- function(clast, cnew) {
  size = dim(clast)[1]
  same = TRUE
  for (i in 1:size) {
    if (clast[i] != cnew[i]) {
      same = FALSE
    }
  }
  return(same)
}

applyKMC <- function(C_initial, X, K, maxIts = 100) { # 
  # Initial Step 1
  mnew = getMeans(C_initial,X,K)
  # Initial Step 2
  cnew = reCluster(X,mnew,K)
  
  its = 1
  
  # Store last cluster assignments to compare
  c_prev = C_initial
  
  # Continue full iterations until we converge 
  # (meaning we see no changes between iterations)
    while (!converged(c_prev,cnew)){
    c_prev = cnew
    mnew = getMeans(c_prev,X,K)
    cnew = reCluster(X,mnew,K)
    its = its + 1
    if (its >= maxIts){ # stop if reached maximum trials
      break
    }
  }
  return(cnew)
}

```

```{r}
n = dim(Xs)[1]
K = 4

# Randomize c0
c0 = matrix(data = 0, nrow = n, ncol = 1)
for (i in 1:n) {
  c0[i] = ceiling(runif(1,min = 0, max = K))
}

maxIters = 50
cfinal = applyKMC(c0,Xs,K,maxIters)
mfinal = getMeans(cfinal,Xs,K)
```

```{r}
# Evaluate our convergence
zimage <- function(vec) {
  img <-   matrix(vec[1:256],nrow=16,ncol=16); 
  img <- t(apply(-img, 1, rev))
  image(img,col=grey(seq(0,1,length=256)))
}

for (i in 1:K) {
  zimage(mfinal[i,])
}
```